Registration form
anshulgupta222/TaskerUI pull request #2
Opened 2022-09-12 09:45 UTC by anshulgupta222

Hi Harsh ,

Could you please approve this PR ?

2022-09-12 11:19 UTC, anshulgupta222 commented on src/app/registration-form/registration-form.component.html
> +<div class="container-md border my-2">
Move this container class to app.component.html

2022-09-12 11:59 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.html
> +<div class="container-md border my-2">
move container div to app.component.html it will be common to every component and should be placed in the parent component

2022-09-12 11:59 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.html
> +    <div *ngIf="form?.errors" class="alert alert-danger">Connection is not establish yet</div>
the message should "Please resolve the errors first"

2022-09-12 12:00 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.html
> +                    <div *ngIf ="firstName?.['touched'] && firstName?.['invalid']" class ="alert alert-danger">
use span instead of div for erros msgs

2022-09-12 12:02 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.html
> +                placeholder="abc@email.com">
no need of this placeholder. Or you can just put the word "email" as placeholder.

2022-09-12 12:05 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.ts
> +import { SpaceValidators} from './space.validators';
please seperate external library imports and your imports with a blank line

2022-09-12 12:06 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.ts
> +  get firstName()
Is this method required? where are we using this method

2022-09-12 12:06 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.ts
> +  get email()
Is this method required? where are we using this method

2022-09-12 12:09 UTC, harshdave71720 commented on src/app/registration-form/registration-form.component.ts
> +    this.form.setErrors({
check if form has errors and only then set the errors

2022-09-12 12:10 UTC, harshdave71720 commented on src/styles.css
> +.container-md{
don't use custom css, use bootstrap for this thing also

2022-09-12 12:10 UTC, harshdave71720 requested changes
Hi Anshul, Please do the changes as commented

2022-09-13 16:56 UTC, anshulgupta222 commented on src/styles.css
> +.container-md{
Registration Form tag moved in bootstrap class container-fluid

2022-09-13 16:57 UTC, anshulgupta222 commented on src/app/registration-form/registration-form.component.html
> +<div class="container-md border my-2">
changes done as requested..

2022-09-13 17:07 UTC, anshulgupta222 commented on src/app/registration-form/registration-form.component.html
> +                    <div *ngIf ="firstName?.['touched'] && firstName?.['invalid']" class ="alert alert-danger">
As discussed, Not required

2022-09-13 17:43 UTC, anshulgupta222 commented on src/app/registration-form/registration-form.component.html
> +    <div *ngIf="form?.errors" class="alert alert-danger">Connection is not establish yet</div>
Error message is update as requested.

2022-09-13 17:43 UTC, anshulgupta222 commented on src/app/registration-form/registration-form.component.html
> +                placeholder="abc@email.com">
Place holder is removed

2022-09-13 17:51 UTC, harshdave71720 approved these changes

2022-09-13 17:52 UTC, merged