Adding Login-Form
anshulgupta222/TaskerUI pull request #3
Opened 2022-09-16 11:35 UTC by anshulgupta222

Hi Harsh ,

Please review this component

2022-09-16 11:37 UTC, harshdave71720 commented on src/app/login-form/login-form.component.html
> +    <div class="text-center my-2" style="font-weight: bold">Login</div>
find bootstrap class for bold text

2022-09-16 11:38 UTC, harshdave71720 commented on src/app/login-form/login-form.component.html
> +              type="text"
change the type to email

2022-09-16 11:38 UTC, harshdave71720 commented on src/app/login-form/login-form.component.html
> +              type="text"
change type to password

2022-09-16 11:40 UTC, harshdave71720 commented on src/app/login-form/login-form.component.ts
> +
add empty method for form submission

2022-09-16 11:41 UTC, harshdave71720 requested changes
Hello Anshul, Please complete the suggested changes

2022-09-16 17:52 UTC, anshulgupta222 commented on src/app/login-form/login-form.component.html
> +    <div class="text-center my-2" style="font-weight: bold">Login</div>
Added the bootstrap class "fw-bold"

2022-09-16 17:53 UTC, anshulgupta222 commented on src/app/login-form/login-form.component.html
> +              type="text"
Added the input type "email"

2022-09-16 17:54 UTC, anshulgupta222 commented on src/app/login-form/login-form.component.ts
> +
Added the method --> login()

2022-09-16 17:54 UTC, anshulgupta222 commented on src/app/login-form/login-form.component.html
> +              type="text"
Added the input type "password"

2022-09-18 14:44 UTC, harshdave71720 approved these changes

2022-09-18 14:44 UTC, merged